### ISSUE TITLE
Game crashes when sending command

### ISSUE THREAD

**Issue by AddictedCoins** [GirafiStudios/MineMenu#144] opened 2022-11-11 18:22 UTC
When my computer is loading the game with the mod, the game could startup fine and is able to join worlds and servers, but whenever I am executing commands using minemenu, the entire game crashes, and I've been trying to fix this problem by switching java version from 17-18-19, and also forge versions from 43.1.1 to 43.1.52(Latest version of forge), but the problem still persists regardless of the java version change or forge version change.

Additional Information:
[Crash Report](https://github.com/GirafiStudios/MineMenu/files/9992567/crash-2022-11-11_10.10.55-client.txt)

Device: MBP 2021 14" M1 Pro

Game Version: 1.19.2

Java Version(Current): Java SE Runtime Environment (build 19.0.1+10-21)

Forge Version(Current): 43.1.52(for 1.19.2)

Mojang/Microsoft Official Minecraft Launcher

Existing Mods:
ItemZoom
JEI
Optifine H9
WorldEdit 7.2.12
MineMenu 1.11.1

**Comment by AddictedCoins** [comment] 2022-11-11 18:25
P.S. Java installed on my mac is ARM64 Native java, not x86 java(so rosetta 2 is not involved)

**Comment by redxtech** [comment] 2022-11-12 21:03
I've also found it crashes whenever I send a command.

I'll update with modlist shortly.

**Comment by AddictedCoins** [comment] 2022-11-12 21:10
> I've also found it crashes whenever I send a command.
> 
> ~I'll update with modlist shortly.~
> 
> It crashes without any other mods enabled for me.

Also on a Apple Silicon Mac?

**Comment by redxtech** [comment] 2022-11-12 21:11
No, I'm on a linux pc, with AMD 5900X CPU & AMD Fury X GPU.

**Comment by AddictedCoins** [comment] 2022-11-12 21:12
> No, I'm on a linux pc, with AMD 5900X CPU & AMD Fury X GPU.

Seems like this is a Unix issue…..

**Comment by redxtech** [comment] 2022-11-12 21:15
> > No, I'm on a linux pc, with AMD 5900X CPU & AMD Fury X GPU.
> 
> Seems like this is a Unix issue…..

Yeah that might be the case. I've edited my comment to include my crash log.

**Comment by AddictedCoins** [comment] 2022-11-13 17:43
> > > No, I'm on a linux pc, with AMD 5900X CPU & AMD Fury X GPU.
> > 
> > 
> > Seems like this is a Unix issue…..
> 
> Yeah that might be the case. I've edited my comment to include my crash log.

But strangely, I just tried to use the mod on a x86_64 MacBook Pro, and nothing happened, everything is fine
Game Version: 1.19.2

Java Version(x86_64 MacBook Pro): Java SE Runtime Environment (build 19.0.1+10-21)

Forge Version(x86_64 MacBook Pro): 43.1.52(for 1.19.2)

**Comment by GirafiStudios** [comment] 2022-12-19 19:14
Closing, as this doesn´t seem to be caused by Mine Menu.

**Closed by GirafiStudios** 2022-12-19 19:14 UTC
