### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by wycats0** [GirafiStudios/MineMenu#152] opened 2023-07-23 01:16 UTC
https://crashy.net/4eab9406-2928-4619-869b-7c9cfe46b85e
[crash-2023-07-22_21.10.25-client.txt](https://github.com/GirafiStudios/MineMenu/files/12137505/crash-2023-07-22_21.10.25-client.txt)

**Comment by GirafiStudios** [comment] 2023-08-01 21:06
Duplicate of https://github.com/GirafiStudios/MineMenu/issues/150

**Closed by GirafiStudios** 2023-08-01 21:06 UTC
