### ISSUE TITLE
[1.16.5] Some Keys Resetting on Restart

### ISSUE THREAD

**Issue by ThanEEpic** [GirafiStudios/MineMenu#118] opened 2021-09-24 02:14 UTC
Same issue as everyone else. I love this mod but I can't include it in my pack if it's not working properly.

**Comment by AndreySlower** [comment] 2021-12-12 01:25
same

**Comment by GirafiStudios** [comment] 2022-07-09 16:24
Duplicate of https://github.com/GirafiStudios/MineMenu/issues/104

**Closed by GirafiStudios** 2022-07-09 16:24 UTC
